// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: proto/heimdall/v1/data_plane.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EvaluateRequest contains the targeting information needed for a decision.
type EvaluateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique key of the feature flag (e.g., "new-checkout").
	FlagKey string `protobuf:"bytes,1,opt,name=flag_key,json=flagKey,proto3" json:"flag_key,omitempty"`
	// The context of the user/entity requesting the flag.
	// In V1, we use a flexible map to allow arbitrary attributes
	// (e.g., {"user_id": "123", "region": "us", "plan": "premium"}).
	// This avoids strict schema coupling between Client and Server.
	Context       map[string]string `protobuf:"bytes,2,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluateRequest) Reset() {
	*x = EvaluateRequest{}
	mi := &file_proto_heimdall_v1_data_plane_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateRequest) ProtoMessage() {}

func (x *EvaluateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_heimdall_v1_data_plane_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateRequest.ProtoReflect.Descriptor instead.
func (*EvaluateRequest) Descriptor() ([]byte, []int) {
	return file_proto_heimdall_v1_data_plane_proto_rawDescGZIP(), []int{0}
}

func (x *EvaluateRequest) GetFlagKey() string {
	if x != nil {
		return x.FlagKey
	}
	return ""
}

func (x *EvaluateRequest) GetContext() map[string]string {
	if x != nil {
		return x.Context
	}
	return nil
}

// EvaluateResponse returns the final decision.
type EvaluateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True if the feature should be enabled for this context.
	Value bool `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	// Reason explains why the decision was made.
	// Examples: "STATIC_OFF", "DEFAULT_VALUE", "RULE_MATCH".
	// Critical for debugging why a user saw a specific version.
	Reason        string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluateResponse) Reset() {
	*x = EvaluateResponse{}
	mi := &file_proto_heimdall_v1_data_plane_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateResponse) ProtoMessage() {}

func (x *EvaluateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_heimdall_v1_data_plane_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateResponse.ProtoReflect.Descriptor instead.
func (*EvaluateResponse) Descriptor() ([]byte, []int) {
	return file_proto_heimdall_v1_data_plane_proto_rawDescGZIP(), []int{1}
}

func (x *EvaluateResponse) GetValue() bool {
	if x != nil {
		return x.Value
	}
	return false
}

func (x *EvaluateResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_proto_heimdall_v1_data_plane_proto protoreflect.FileDescriptor

const file_proto_heimdall_v1_data_plane_proto_rawDesc = "" +
	"\n" +
	"\"proto/heimdall/v1/data_plane.proto\x12\vheimdall.v1\"\xad\x01\n" +
	"\x0fEvaluateRequest\x12\x19\n" +
	"\bflag_key\x18\x01 \x01(\tR\aflagKey\x12C\n" +
	"\acontext\x18\x02 \x03(\v2).heimdall.v1.EvaluateRequest.ContextEntryR\acontext\x1a:\n" +
	"\fContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"@\n" +
	"\x10EvaluateResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\bR\x05value\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason2T\n" +
	"\tDataPlane\x12G\n" +
	"\bEvaluate\x12\x1c.heimdall.v1.EvaluateRequest\x1a\x1d.heimdall.v1.EvaluateResponseB0Z.github.com/rafaeljc/heimdall/proto/heimdall/v1b\x06proto3"

var (
	file_proto_heimdall_v1_data_plane_proto_rawDescOnce sync.Once
	file_proto_heimdall_v1_data_plane_proto_rawDescData []byte
)

func file_proto_heimdall_v1_data_plane_proto_rawDescGZIP() []byte {
	file_proto_heimdall_v1_data_plane_proto_rawDescOnce.Do(func() {
		file_proto_heimdall_v1_data_plane_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_heimdall_v1_data_plane_proto_rawDesc), len(file_proto_heimdall_v1_data_plane_proto_rawDesc)))
	})
	return file_proto_heimdall_v1_data_plane_proto_rawDescData
}

var file_proto_heimdall_v1_data_plane_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_heimdall_v1_data_plane_proto_goTypes = []any{
	(*EvaluateRequest)(nil),  // 0: heimdall.v1.EvaluateRequest
	(*EvaluateResponse)(nil), // 1: heimdall.v1.EvaluateResponse
	nil,                      // 2: heimdall.v1.EvaluateRequest.ContextEntry
}
var file_proto_heimdall_v1_data_plane_proto_depIdxs = []int32{
	2, // 0: heimdall.v1.EvaluateRequest.context:type_name -> heimdall.v1.EvaluateRequest.ContextEntry
	0, // 1: heimdall.v1.DataPlane.Evaluate:input_type -> heimdall.v1.EvaluateRequest
	1, // 2: heimdall.v1.DataPlane.Evaluate:output_type -> heimdall.v1.EvaluateResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_heimdall_v1_data_plane_proto_init() }
func file_proto_heimdall_v1_data_plane_proto_init() {
	if File_proto_heimdall_v1_data_plane_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_heimdall_v1_data_plane_proto_rawDesc), len(file_proto_heimdall_v1_data_plane_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_heimdall_v1_data_plane_proto_goTypes,
		DependencyIndexes: file_proto_heimdall_v1_data_plane_proto_depIdxs,
		MessageInfos:      file_proto_heimdall_v1_data_plane_proto_msgTypes,
	}.Build()
	File_proto_heimdall_v1_data_plane_proto = out.File
	file_proto_heimdall_v1_data_plane_proto_goTypes = nil
	file_proto_heimdall_v1_data_plane_proto_depIdxs = nil
}
