// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: heimdall/v1/data_plane.proto

package heimdallv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	DataPlaneService_Evaluate_FullMethodName = "/heimdall.v1.DataPlaneService/Evaluate"
)

// DataPlaneServiceClient is the client API for DataPlaneService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DataPlaneServiceClient interface {
	// Evaluate checks a specific flag against a user context.
	Evaluate(ctx context.Context, in *EvaluateRequest, opts ...grpc.CallOption) (*EvaluateResponse, error)
}

type dataPlaneServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDataPlaneServiceClient(cc grpc.ClientConnInterface) DataPlaneServiceClient {
	return &dataPlaneServiceClient{cc}
}

func (c *dataPlaneServiceClient) Evaluate(ctx context.Context, in *EvaluateRequest, opts ...grpc.CallOption) (*EvaluateResponse, error) {
	out := new(EvaluateResponse)
	err := c.cc.Invoke(ctx, DataPlaneService_Evaluate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataPlaneServiceServer is the server API for DataPlaneService service.
// All implementations must embed UnimplementedDataPlaneServiceServer
// for forward compatibility
type DataPlaneServiceServer interface {
	// Evaluate checks a specific flag against a user context.
	Evaluate(context.Context, *EvaluateRequest) (*EvaluateResponse, error)
	mustEmbedUnimplementedDataPlaneServiceServer()
}

// UnimplementedDataPlaneServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDataPlaneServiceServer struct {
}

func (UnimplementedDataPlaneServiceServer) Evaluate(context.Context, *EvaluateRequest) (*EvaluateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Evaluate not implemented")
}
func (UnimplementedDataPlaneServiceServer) mustEmbedUnimplementedDataPlaneServiceServer() {}

// UnsafeDataPlaneServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataPlaneServiceServer will
// result in compilation errors.
type UnsafeDataPlaneServiceServer interface {
	mustEmbedUnimplementedDataPlaneServiceServer()
}

func RegisterDataPlaneServiceServer(s grpc.ServiceRegistrar, srv DataPlaneServiceServer) {
	s.RegisterService(&DataPlaneService_ServiceDesc, srv)
}

func _DataPlaneService_Evaluate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EvaluateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataPlaneServiceServer).Evaluate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataPlaneService_Evaluate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataPlaneServiceServer).Evaluate(ctx, req.(*EvaluateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DataPlaneService_ServiceDesc is the grpc.ServiceDesc for DataPlaneService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataPlaneService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "heimdall.v1.DataPlaneService",
	HandlerType: (*DataPlaneServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Evaluate",
			Handler:    _DataPlaneService_Evaluate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "heimdall/v1/data_plane.proto",
}
