# Stage 1: Build
FROM golang:1.24-alpine AS builder

WORKDIR /app

COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /main ./cmd/heimdall-syncer

# Stage 2: Run
FROM alpine:latest

WORKDIR /root/

ARG HEALTH_PORT=9090
ENV HEIMDALL_HEALTH_PORT=${HEALTH_PORT}

COPY --from=builder /main .

EXPOSE ${HEIMDALL_HEALTH_PORT}

CMD ["./main"]
