# Stage 1: Build
FROM golang:1.24-alpine AS builder

WORKDIR /app

COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /main ./cmd/heimdall-data

# Stage 2: Run
FROM alpine:latest

WORKDIR /root/
COPY --from=builder /main .

EXPOSE 50051

CMD ["./main"]
