
version: '3'

vars:
  BIN_DIR: bin
  PROTO_DIR: proto

tasks:
  default:
    desc: Lists available tasks
    cmds:
      - task --list

  # --- DEVELOPMENT WORKFLOW (dev:*) ---
  dev:up:
    desc: Starts the local environment (builds images and starts containers)
    cmds:
      # build ensures that if you change main.go, the image is recreated
      - docker compose up -d --build
      - echo "Heimdall environment is running!"
      - echo "Control API at http://localhost:8080"
      - echo "Swagger UI at http://localhost:8081"

  dev:down:
    desc: Stops the local environment (stops containers and removes networks)
    cmds:
      - docker compose down
      - echo "Environment stopped."

  dev:reset:
    desc: Destroys ALL data volumes (Clean Start)
    cmds:
      - docker compose down -v
      - echo "Destroyed all data volumes. Run 'task dev:up' to start fresh."

  dev:logs:
    desc: Tails logs from all running services
    cmds:
      - docker compose logs -f
  
  # --- QUALITY & TESTING (check:* / test:*) ---
  check:lint:
    desc: Runs golangci-lint
    cmds:
      - golangci-lint run ./...

  test:unit:
    desc: Runs unit tests
    cmds:
      - go test ./... -v

  test:integration:
    desc: Runs integration tests
    cmds:
      - go test ./... -v -tags=integration

  # --- BUILD (build:*) ---
  build:local:
    desc: Builds all Go binaries locally to /bin
    cmds:
      - mkdir -p {{.BIN_DIR}}
      - go build -o {{.BIN_DIR}}/heimdall-control ./cmd/heimdall-control
      - go build -o {{.BIN_DIR}}/heimdall-data ./cmd/heimdall-data
      - go build -o {{.BIN_DIR}}/heimdall-syncer ./cmd/heimdall-syncer
    sources:
      - ./**/*.go

  build:docker:
    desc: Builds Production Docker images for all services
    cmds:
      - docker build -f Dockerfile.control-plane -t heimdall-control:latest .
      - docker build -f Dockerfile.data-plane -t heimdall-data:latest .
      - docker build -f Dockerfile.syncer -t heimdall-syncer:latest .

  # --- CODE GENERATION (generate:*) ---
  generate:proto:
    desc: Generates Go code from .proto files
    cmds:
      - protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative {{.PROTO_DIR}}/heimdall/v1/*.proto
    sources:
      - '{{.PROTO_DIR}}/**/*.proto'
    generates:
      - '{{.PROTO_DIR}}/**/*.pb.go'

  # --- SECURITY (sec:*) ---
  sec:genkey:
    desc: Generates a secure random API key (32 bytes, base64-encoded)
    silent: true
    cmds:
      - |
        set +o history 2>/dev/null || true  # Disable history logging
        set +x  # Disable command echoing
        KEY=$(openssl rand -base64 32)
        HASH=$(printf '%s' "$KEY" | sha256sum | cut -d' ' -f1)
        
        printf "\n"
        printf "===================================================================\n"
        printf "           HEIMDALL API KEY - STORE SECURELY\n"
        printf "===================================================================\n"
        printf "\n"
        printf "API Key (use in Authorization header):\n"
        printf "%s\n" "$KEY"
        printf "\n"
        printf "-------------------------------------------------------------------\n"
        printf "\n"
        printf "SHA-256 Hash (set as API_KEY_HASH env var):\n"
        printf "%s\n" "$HASH"
        printf "\n"
        printf "===================================================================\n"
        printf "SECURITY NOTICE:\n"
        printf "  - Store the API Key in a secure location (password manager)\n"
        printf "  - Set API_KEY_HASH in your environment/secrets manager\n"
        printf "  - Never commit the key or hash to version control\n"
        printf "  - This information will not be displayed again\n"
        printf "===================================================================\n"
        printf "\n"
        
        # Clear sensitive variables from memory
        unset KEY HASH
        set -o history 2>/dev/null || true  # Re-enable history

  sec:hash:
    desc: Computes SHA-256 hash for an existing API key
    silent: true
    cmds:
      - |
        set +o history 2>/dev/null || true  # Disable history logging
        set +x  # Disable command echoing
        
        # Prompt for API key without echoing to terminal
        printf "Enter API Key: " >&2
        read -rs KEY
        printf "\n" >&2
        
        if [ -z "$KEY" ]; then
          printf "Error: API key cannot be empty\n" >&2
          exit 1
        fi
        
        HASH=$(printf '%s' "$KEY" | sha256sum | cut -d' ' -f1)
        
        printf "\n"
        printf "SHA-256 Hash (set as API_KEY_HASH env var):\n"
        printf "%s\n" "$HASH"
        printf "\n"
        
        # Clear sensitive variables from memory
        unset KEY HASH
        set -o history 2>/dev/null || true  # Re-enable history

  # --- DEPENDENCY MANAGEMENT (tidy:*) ---
  tidy:deps:
    desc: Runs go mod tidy forcing Go 1.23 compatibility
    cmds:
      - go mod tidy -go=1.23.0
