apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

resources:
  - hpa.yaml
  - external-secret.yaml

patches:
  - path: deployment-patch.yaml

# Kustomize automatically hashes this ConfigMap to trigger rolling restarts upon changes
configMapGenerator:
  - name: heimdall-syncer-config
    literals:
      - HEIMDALL_APP_ENV=production
      - HEIMDALL_APP_LOG_LEVEL=info
      - HEIMDALL_APP_LOG_FORMAT=json
      - HEIMDALL_DB_SSL_MODE=require
      - HEIMDALL_REDIS_TLS_ENABLED=true
      # Leverage the Optimistic Locking architecture by allowing high concurrency during hydration
      - HEIMDALL_SYNCER_HYDRATION_CONCURRENCY=20
