package controlapi

import (
	"log/slog"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5/middleware"
	"github.com/rafaeljc/heimdall/internal/logger"
)

// RequestLogger creates a middleware that handles structured logging for HTTP requests.
// It performs three main tasks:
// 1. Derives a request-scoped logger enriched with the Request ID.
// 2. Injects this logger into the context for downstream handlers to use.
// 3. Logs the final outcome of the request (latency, status, method).
func RequestLogger(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		start := time.Now()

		// 1. Resolve Request ID
		// Leverages Chi's RequestID middleware. Ensure Chi's middleware is mounted BEFORE this one.
		reqID := middleware.GetReqID(r.Context())
		if reqID == "" {
			reqID = "unknown" // Fallback safety
		}

		// 2. Create Contextual Logger
		// We take the configured default logger and create a child logger that
		// PERMANENTLY attaches the request_id to every log line generated by this request.
		reqLogger := slog.Default().With(
			slog.String("request_id", reqID),
		)

		// 3. Inject Logger into Context
		// Now, handlers like 'handleCreateFlag' can simply call logger.FromContext(ctx)
		// and get this pre-configured logger instance.
		ctx := logger.WithContext(r.Context(), reqLogger)

		// 4. Wrap ResponseWriter (Chi helper) to capture status code
		ww := middleware.NewWrapResponseWriter(w, r.ProtoMajor)

		// 5. Process Request (Passing the NEW context with the logger)
		next.ServeHTTP(ww, r.WithContext(ctx))

		// 6. Log Outcome
		duration := time.Since(start)
		status := ww.Status()

		// Dynamic Log Level based on Status Code
		level := slog.LevelInfo
		if status >= 500 {
			level = slog.LevelError
		} else if status >= 400 {
			level = slog.LevelWarn
		}

		// We use the reqLogger to emit this log.
		// Note: We don't need to pass "request_id" here again, it's already in the logger.
		reqLogger.Log(ctx, level, "http request completed",
			slog.String("method", r.Method),
			slog.String("path", r.URL.Path),
			slog.Int("status", status),
			slog.String("duration", duration.String()),
			slog.String("remote_ip", r.RemoteAddr),
		)
	})
}
